"""
MockProvider — a deterministic, fully local stand-in for a real language
model. It lets every layer of Commandra Brain (planning, reasoning, context
selection, agents, response optimization) be built and tested end-to-end
without any model server running.

It does not "hallucinate" free-form prose. Instead it reflects back a
structured, useful answer built from the prompt it was given, so that the
whole pipeline can be exercised deterministically in tests and in local
development before Ollama is wired up.
"""

from __future__ import annotations

import re
import time
from typing import Iterator

from providers.ai_provider import (
    AIProvider,
    GenerationRequest,
    GenerationResult,
)


class MockProvider(AIProvider):
    """Deterministic offline provider used for development and testing."""

    def __init__(self, latency_seconds: float = 0.0) -> None:
        self._latency = latency_seconds

    @property
    def name(self) -> str:
        return "mock"

    def is_available(self) -> bool:
        return True

    def _synthesize(self, request: GenerationRequest) -> str:
        prompt = request.prompt
        first_line = next((l for l in prompt.splitlines() if l.strip()), "")
        task = first_line.strip()[:160]

        file_mentions = re.findall(r"^--- (.+?) ---$", prompt, flags=re.MULTILINE)
        files_note = (
            f"Reviewed {len(file_mentions)} context file(s): "
            + ", ".join(file_mentions[:6])
            + ("..." if len(file_mentions) > 6 else "")
            if file_mentions
            else "No repository context was supplied for this request."
        )

        return (
            f"## Mock Response\n\n"
            f"This is a deterministic offline response generated by "
            f"`MockProvider` (no language model was called).\n\n"
            f"**Understood task:** {task or 'general request'}\n\n"
            f"**Context awareness:** {files_note}\n\n"
            f"Once Commandra Nox Brain is connected to Ollama "
            f"(see `docs/OLLAMA_SETUP.md`), this response will be replaced "
            f"by real, model-generated reasoning and code.\n"
        )

    def generate(self, request: GenerationRequest) -> GenerationResult:
        if self._latency:
            time.sleep(self._latency)
        text = self._synthesize(request)
        return GenerationResult(
            text=text,
            provider=self.name,
            model="mock-echo-1",
            prompt_tokens_estimate=len(request.prompt) // 4,
            completion_tokens_estimate=len(text) // 4,
            raw={"mock": True},
        )

    def stream(self, request: GenerationRequest) -> Iterator[str]:
        text = self._synthesize(request)
        for chunk in re.findall(r".{1,40}(?:\s+|$)", text):
            if self._latency:
                time.sleep(self._latency / 20)
            yield chunk
