"""
Documentation Generator -- turns repository metadata already computed by
other engines (architecture summary, package managers) into clean Markdown
docs: README, architecture overview, installation guide. No AI calls here;
this is deterministic templating over structured data the brain already has.
"""

from __future__ import annotations


def generate_readme(
    repo_id: str,
    narrative: str,
    install_cmd: str | None = None,
    extra: str | None = None,
) -> str:
    lines = [f"# {repo_id}", ""]

    if narrative:
        lines += [narrative.strip(), ""]
    else:
        lines += ["_No architecture summary available yet -- index the repository to generate one._", ""]

    lines += ["## Getting Started", ""]
    if install_cmd:
        lines += ["```bash", install_cmd, "```", ""]
    else:
        lines += ["_No package manager detected. Add installation steps here._", ""]

    if extra:
        lines += [extra.strip(), ""]

    lines += ["## Generated By", "", "This README was generated by Commandra Nox's Documentation Agent.", ""]
    return "\n".join(lines)


def generate_architecture_doc(arch: dict) -> str:
    lines = ["# Architecture Overview", ""]

    narrative = arch.get("narrative")
    if narrative:
        lines += [narrative.strip(), ""]

    pattern = arch.get("pattern")
    if pattern:
        lines += [f"**Detected/selected pattern:** {pattern}", ""]

    layers = arch.get("layers")
    if layers:
        lines += ["## Layers", ""]
        lines += [f"- {layer}" for layer in layers]
        lines += [""]

    components = arch.get("components") or arch.get("modules")
    if components:
        lines += ["## Components", ""]
        for c in components:
            if isinstance(c, dict):
                name = c.get("name", "unnamed")
                desc = c.get("description", "")
                lines.append(f"- **{name}**: {desc}" if desc else f"- **{name}**")
            else:
                lines.append(f"- {c}")
        lines += [""]

    if len(lines) <= 2:
        lines += ["_No architecture details available yet -- index the repository first._", ""]

    return "\n".join(lines)


def generate_installation_guide(package_managers: list[dict]) -> str:
    if not package_managers:
        return "# Installation\n\n_No package manager detected in this repository._\n"

    lines = ["# Installation", ""]
    for pm in package_managers:
        name = pm.get("name") or pm.get("manager") or "unknown"
        install_cmd = pm.get("install_command") or pm.get("installCommand")
        lockfile = pm.get("lockfile")

        lines.append(f"## {name}")
        if lockfile:
            lines.append(f"Lockfile detected: `{lockfile}`")
        if install_cmd:
            lines += ["```bash", install_cmd, "```"]
        lines.append("")

    return "\n".join(lines)
